#!/bin/bash
# Preparation script to run BEFORE starting Cursor
# Kills any existing MCP servers to prevent conflicts

echo "🧹 Preparing environment for Cursor..."

# Kill any existing MCP servers
if pgrep -f "rag_context.interfaces.mcp_server" > /dev/null; then
    echo "🛑 Killing existing MCP servers..."
    pkill -f "rag_context.interfaces.mcp_server" || true
    sleep 2
    echo "✅ MCP servers terminated"
else
    echo "✅ No existing MCP servers found"
fi

# Check if struct.json exists and is recent
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

if [ ! -f "$PROJECT_ROOT/struct.json" ]; then
    echo "⚠️  struct.json not found - will be generated by MCP server if needed"
elif [ "$(find "$PROJECT_ROOT/struct.json" -mtime +1)" ]; then
    echo "⚠️  struct.json is older than 1 day - consider regenerating"
fi

echo "🚀 Environment ready for Cursor startup!"
echo "💡 Cursor will automatically start MCP server with proper configuration"
echo "" 